project:
  type: website
  output-dir: docs
  resources:
    - extras/**
  
# Meta
description-meta: "VARICRIS research project"
author-meta: "Christian Rauh / Christian Kreuder-Sonnen"

execute:
  freeze: false
  cache: false

# SEO niceties
sitemap: true
lang: en

  
website:
  title: "VARICRIS"
  
  open-graph: true   # optional, for better link previews
  
  navbar:
    left:
      - href: project.qmd
        text: Project
      - href: people.qmd
        text: People
      - href: output.qmd
        text: Output
      - href: crisisdata.qmd
        text: Crisis Data
        
  page-footer:
    left: "&copy; <script>document.write(new Date().getFullYear())</script> Christian Kreuder-Sonnen / Christian Rauh"

    
  repo-url: https://github.com/ChRauh/varicrisis/

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true
    link-external-newwindow: true
    email-obfuscation: javascript
    include-after-body: |
      <script>
        document.addEventListener("DOMContentLoaded", function() {
          const links = document.querySelectorAll("a[href^='http']");
          const host = window.location.hostname;
          links.forEach(link => {
            if (!link.href.includes(host)) {
              link.setAttribute("target", "_blank");
              link.setAttribute("rel", "noopener noreferrer");
            }
          });
        });
      </script>



